config/routes.rb
Rails.application.routes.draw do

  get 'images/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "pages#index"

  resources :posts do
    resources :postcomments
   end

resources :photos do 
    member do 
      get :vote
    end
  end
  
resources :images do
    member do
      get :voteforphoto
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :photos ,dependent: :destroy

end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	belongs_to :user
	belongs_to :category
	has_many :votes, dependent: :destroy

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomment, dependent: :destroy
	validates :title,:body, presence: true
	validates :title, length: { in: 3..20 }
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :postcomments, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :voteforphotos, dependent: :destroy


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :nickname, :email, :password, :password_confirmation, presence: true
  validates :nickname, length: { in: 6..20 }
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :user
	belongs_to :photo
end

app/models/vote_for_photo.rb
class VoteForPhoto < ApplicationRecord
  belongs_to :user
  belongs_to :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :divise_sign_up_params, if: :devise_controller?
	protect_from_forgery with: :exception

private

	def divise_sign_up_params
		devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :nickname, :avatar])
	end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
before_action :authenticate_user!
before_action :image_set, only:[:destroy, :vote]

	def index
    	@images = Image.all
    	@like = {}
    	@images.each do |image|
      		@voteforphotos = VoteForPhoto.where(image_id: image.id).sum(:like)
      		@like[image.id] = @voteforphotos
    	end
  	end

	def new

	end

	def create
		@user = current_user

		if params[:images]
			params[:images].each {|image|
				@files = @user.images.create(image: image)}
		end
		redirect_to images_path
	end

	def destroy
    	@image.destroy
    	redirect_to images_path
    end

    def voteforphoto
    @image = Image.find(params[:id])
    @voteforphoto = VoteForPhoto.where(user_id: current_user.id, image_id: @image.id).first
    if @voteforphoto == nil
       @like = 1
       VoteForPhoto.create(user_id: current_user.id, image_id: @image.id, like: @like)
     elsif @voteforphoto.like == 0
       @voteforphoto.update(like: @voteforphoto.like + 1)
     else
       @voteforphoto.update(like: @voteforphoto.like - 1)
    end
    redirect_to images_path
  end

private

def image_params
	params.require(:images).permit(:user_id, :image)
end

def image_set
    pp @image = Image.find(params[:id])
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	pp @posts = Post.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!
 	before_action :photo_set, only:[:show, :edit, :update, :destroy, :vote]

	def index
		@photos = Photo.all	
		@like = {}
		@photos.each do |photo|
			@votes = Vote.where(photo_id: photo.id).sum(:like)
			@like[photo.id] = @votes
		end
	end

	def new
		@photo = Photo.new
	end

	def create	
		params[:photo][:category_id] = params[:category_id]
		params[:photo][:user_id] = current_user.id
		pp @photo = Photo.create(photo_params)
		redirect_to photos_path
	end

	def edit

  	end

	def update		
		params[:photo][:user_id] = @photo.user_id
    	params[:photo][:category_id] = @photo.category_id
    	@photo.update(photo_params)
    	redirect_to 'photos'
  	end

	def destroy		
 		@photo.destroy
 		redirect_to photos_path
  	end

  def vote
    @photo = Photo.find(params[:id])
    @vote = Vote.where(user_id: current_user.id, photo_id: @photo.id).first
    if @vote == nil
       @like = 1
       Vote.create(user_id: current_user.id, photo_id: @photo.id, like: @like)
    elsif @vote.like == 0
         @vote.update(like: @vote.like + 1)
    else
       @vote.update(like: @vote.like - 1)
    end
    redirect_to photos_path
  end

private

	def photo_params
		params.require(:photo).permit(:user_id, :category_id,:name, :photo)
	end

	def photo_set
		pp @photo = Photo.find(params[:id])
  		
  	end

end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController
before_action :authenticate_user!
before_action :find_post, only:[:update, :edit]
before_action :set_comment, only:[:edit, :update, :destroy]

  def create
    params[:postcomment][:post_id] = params[:post_id]
    params[:postcomment][:user_id] = current_user.id
    @comment = Postcomment.create(comment_params)
    if @comment.save
      redirect_to post_path(params[:post_id])
      else
        @comment.errors.full_messages.each do |msg|
          @msg = msg
      end
      flash[:notice] = "#{@msg}"
      redirect_to post_path(params[:post_id])
    end
  end

  def edit
    
  end

  def update
    if pp @comment.update(comment_params)
        redirect_to post_path(params[:post_id])
    else
      render 'edit'
    end
  end

  def destroy 
    @comment.destroy
    redirect_to post_path(params[:post_id])
  end

private

  def comment_params
    params.require(:postcomment).permit(:user_id, :post_id, :comment)
  end

  def set_comment  
    pp @comment = Postcomment.find(params[:id])
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!
before_action :set_post, only:[:show, :edit, :update, :destroy]

  def show
    pp @comment = @post.postcomment
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else 
    render 'new'  
    end 
      
  end

  def edit

  end

  def update
    @post.update(post_params)
    redirect_to root_path
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

private

  def post_params
    params.require(:post).permit(:user_id, :title, :body)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/images/_form.html.erb
<%= f.label "Upload Images" %><br>

<%= file_field_tag "images[]", type: :file, multiple: true %>

<p><%= f.submit "Upload" %></p>

app/views/images/index.html.erb
<%= link_to "Upload new foto", new_photo_path , class: "btn btn-default"%>
<%= link_to "Upload multiple image", new_image_path , class: "btn btn-default"%>
<br>
<% if @images == [] %>
	There is no images yet
<% else %>
	<% @images.each do |image| %>
	<%= image_tag image.image.url, width: 200, height: 200 %>
	<p>User:  <%= image.user.nickname %></p>
	<%= link_to "Like", voteforphoto_image_path(image.id) %>
	(<%= @like[image.id] %>)
	<p><% if current_user != nil and current_user.id == image.user_id %>
		<%= link_to "Edit", edit_image_path(image.id) %>
		<%= link_to "Delete", image_path(image.id), data: {confim: 'Are you sure?'}, method: :delete %>
	<% end %>
	</p>
	<% end %>
<% end %> 

app/views/images/new.html.erb
<%= form_for :images, url: images_path, html: {multipart: true} do |f|%>


<%= render 'images/form' , f:f %>

<% end %>

app/views/photos/_form.html.erb
	<p><%= f.label :category %></p>
	<%= select_tag "category_id", options_from_collection_for_select(Category.all, :id,:name) %>


	<p><%= f.label :name %></p>
	<%= f.text_field :name %><br/>

	<p><%= f.label "Upload Photo" %></p>
	<%= f.file_field :photo %>

	<p><%= f.submit "Save" %></p>

app/views/photos/edit.html.erb
<%= form_for @photo, url: photos_path, method: :patch do |f|%>


<%= render 'photos/form' , f:f %>

<%= @photo.user_id %><br/>
<%= @photo.category_id %><br/>
<%= @photo.name %><br/>
<%= @photo.photo_url %><br/>

<% end %>

app/views/photos/index.html.erb
<%= link_to "Upload new foto", new_photo_path , class: "btn btn-default"%>
<%= link_to "Upload multiple image", new_image_path , class: "btn btn-default"%>
<br>

<% if @photos == [] %>
	There is no photos yet.
<% else %>
	<% @photos.each do |photo| %>
	<div class="col-md-3">
	<%= image_tag photo.photo_url, width: 200, height: 200 %>
	<p><b>Name^   </b><%= photo.name %></p>
	<p><b>Category^   </b><%= photo.category.name %></p>
	<p><b>User^   </b><%= photo.user.nickname %></p>

	<p><% if current_user != nil and current_user.id == photo.user_id %>
		<%= link_to "Edit", edit_photo_path(photo.id) %>
		<%= link_to "Delete", photo_path(photo.id), data: {confim: 'Are you sure?'}, method: :delete %>
		
	<% end %>
	</p>
	<p><%= link_to "Like", vote_photo_path(photo.id) %>
	(<%= @like[photo.id] %>)</p>
 	</div>
	<% end %>
<% end %> 		

app/views/photos/new.html.erb
<%= form_for @photo, url: photos_path, validate: true do |f|%>


<%= render 'photos/form' , f:f %>

<% end %>

app/views/postcomments/_form.html.erb
<% if flash[:notice] %>

		<div class="notice"><%= flash[:notice] %></div>

	<% end %>



	<p><%= f.label "Add your comment" %></p>

	<p><%= f.text_area :comment, cols: 5,rows: 5 %></p>

	<%= f.submit "Add Comment" %> 

app/views/postcomments/edit.html.erb
<%= form_for([@post, @comment]) do |f| %>

	<%= render 'postcomments/form' , f:f %>

<% end %>	

app/views/postcomments/new.html.erb
<h1>Postcomments#new</h1>
<p>Find me in app/views/postcomments/new.html.erb</p>

app/views/posts/_form.html.erb
	<p><%= f.label :title %></p>
	<%= f.text_field :title %><br/>

	<p><%= f.label :body %></p>
	<%= f.text_area :body, :class => "tinymce",:rows => 15, :cols => 30%><br/>
	<%= tinymce %>

	<p><%= f.submit "Save" %></p>

app/views/posts/edit.html.erb
<%= form_for :post, url: post_path, method: :patch do |f|%>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
<% end %>

<%= render 'posts/form' , f:f %>

<% end %>

app/views/posts/new.html.erb
<%= form_for @post, url: posts_path, validate: true do |f|%>


<%= render 'posts/form' , f:f %>

<% end %>

app/views/posts/show.html.erb
<div class="center-container">
	<div class="text-center">
<h1><%= @post.title %></h1>
<p>
	Author:<%= @post.user.nickname %> |
	Created at:<%= @post.created_at %> |
	Update at:<%= @post.updated_at %>
</p>
<p><%= sanitize(@post.body) %></p>

</div>


<%= form_for :postcomment ,url: post_postcomments_path(@post.id), method: :post do |f| %>
	
	<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>

	<p><%= f.label "Add your comment" %></p>
	<p><%= f.text_area :comment, cols: 5,rows: 5 %></p>
	<%= f.submit "Add Comment" %>
<% end %>	

<% @comment.each do |comment| %>
<hr>
<%= image_tag comment.user.avatar.url, width: 30, height: 30 %>
<p>User <b><%= comment.user.nickname %></b> say: </p>
<p><%= comment.comment %></p>
<% if current_user != nil and current_user.id == comment.user_id %>
		<p>
		<%= link_to "Edit", edit_post_postcomment_path(@post, comment) %>
 		<%= link_to "Delete", [comment.post, comment], data: {confirm: 'Are you sure?'}, method: :delete %>

 		
 		</p>
	<% end %>
<hr>
<% end %>
</div>
<%=render 'layouts/rightbar'%>