config/routes.rb
Rails.application.routes.draw do

  get 'images/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "pages#index"

  resources :posts do
    resources :postcomments
   end

resources :photos do 
    member do 
      get :vote
    end
  end
  
resources :images do
    member do
      get :voteforphoto
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :photos ,dependent: :destroy

end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	belongs_to :user
	belongs_to :category
	has_many :votes, dependent: :destroy

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomment, dependent: :destroy
	validates :title,:body, presence: true
	validates :title, length: { in: 3..20 }
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :postcomments, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :voteforphotos, dependent: :destroy


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :nickname, :email, :password, :password_confirmation, presence: true
  validates :nickname, length: { in: 6..20 }
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :user
	belongs_to :photo
end

app/models/vote_for_photo.rb
class VoteForPhoto < ApplicationRecord
  belongs_to :user
  belongs_to :image
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
before_action :authenticate_user!
before_action :image_set, only:[:destroy, :vote]

	def index
    	@images = Image.all
    	@like = {}
    	@images.each do |image|
      		@voteforphotos = VoteForPhoto.where(image_id: image.id).sum(:like)
      		@like[image.id] = @voteforphotos
    	end
  	end

	def new

	end

	def create
		@user = current_user

		if params[:images]
			params[:images].each {|image|
				@files = @user.images.create(image: image)}
		end
		redirect_to images_path
	end

	def destroy
    	@image.destroy
    	redirect_to images_path
    end

    def voteforphoto
    @image = Image.find(params[:id])
    @voteforphoto = VoteForPhoto.where(user_id: current_user.id, image_id: @image.id).first
    if @voteforphoto == nil
       @like = 1
       VoteForPhoto.create(user_id: current_user.id, image_id: @image.id, like: @like)
     elsif @voteforphoto.like == 0
       @voteforphoto.update(like: @voteforphoto.like + 1)
     else
       @voteforphoto.update(like: @voteforphoto.like - 1)
    end
    redirect_to images_path
  end

private

def image_params
	params.require(:images).permit(:user_id, :image)
end

def image_set
    pp @image = Image.find(params[:id])
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	pp @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!
before_action :set_post, only:[:show, :edit, :update, :destroy]

  def show
    pp @comment = @post.postcomment
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else 
    render 'new'  
    end 
      
  end

  def edit

  end

  def update
    @post.update(post_params)
    redirect_to root_path
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

private

  def post_params
    params.require(:post).permit(:user_id, :title, :body)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer" style="position: fixed;
    left: 0; bottom: 0;
    text-align: center;
    padding: 10px;
    background: #E87AC3;
    color: #fff;
    width: 100%;">
  Copyright by AnastasiaBetsa
</div>

app/views/layouts/_navbar.html.erb
<div class="header">
          <nav class="navbar navbar-default">
              <div class="agileits-logo">
                <h1><div class="navbar-brand"><%= link_to "Простір для особистості)" , root_path %></div></h1>
              </div>

            <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav navbar-right">
                  <li class="active"><%= link_to "Home" , root_path %></li>                  
                  <li><a href="#news" class="scroll">News</a></li>
                  <li><%= link_to "Gallery", photos_path %></li>
                  <li><a href="#about" class="scroll">About</a></li>
                  <% if current_user.nil? %>
                    <li>
                      <%= link_to new_user_session_path do %>
                        <i class="glyphicon glyphicon-user"></i></span> Login
                        <% end %>
                    <li>
                      <% else %>
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="glyphicon glyphicon-log-out"></i></span> Logout
                        <% end %>
                    <li>
                  <% end %>
                </ul>

            </div>
          </nav>
</div>

app/views/layouts/_rightbar.html.erb
<div class="right-container center-block">
		<%= link_to "Create New Post", new_post_path , class: "btn btn-default"%>
 </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>blogggggg</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/navbar'%>
    <%= yield %>
   <%= render 'layouts/footer'%> 
  </body>
</html>

app/views/pages/index.html.erb
<div class="center-container">
<% @posts.each do |post| %>
 	<div class="col-md-6 post text-center">
	<h1><%= link_to post.title , post_path(post.id)%></h1>
	<p>
	<%= image_tag post.user.avatar.url, width: 30, height: 30 %>
		Author:<%= post.user.nickname %> <br>
		<p><%= sanitize(post.body) %></p>
		Created at:<%= post.created_at %> <br>
		Update at:<%= post.updated_at %> <br>
	</p>

	<% if current_user != nil and current_user.id == post.user_id %>
		<%= link_to "Edit", edit_post_path(post.id) %>
	<%= link_to "Delete", post_path(post.id), data: {confirm: 'Are you sure?'}, method: :delete %>
		<% end %>
	</div>

<% end %>

</div>
<%=render 'layouts/rightbar'%> 